import Head from 'next/head';

import { Header } from 'components/organisms/Header';
import { WelcomeSection } from 'components/templates/WelcomeSection';

const Home = (): JSX.Element => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <WelcomeSection />
            <main>main</main>

            <footer>footer</footer>
        </div>
    );
};
export default Home;
